package com.itizwhatitiz.geliuparduotuve.mybatis.model;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.ID
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.AMOUNT
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.IMAGE
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.NAME
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.PRICE
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.SELLER_ID
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    private Integer sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.DESCRIPTION
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.ID
     *
     * @return the value of PUBLIC.ITEM.ID
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.ID
     *
     * @param id the value for PUBLIC.ITEM.ID
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.AMOUNT
     *
     * @return the value of PUBLIC.ITEM.AMOUNT
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.AMOUNT
     *
     * @param amount the value for PUBLIC.ITEM.AMOUNT
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.IMAGE
     *
     * @return the value of PUBLIC.ITEM.IMAGE
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.IMAGE
     *
     * @param image the value for PUBLIC.ITEM.IMAGE
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.NAME
     *
     * @return the value of PUBLIC.ITEM.NAME
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.NAME
     *
     * @param name the value for PUBLIC.ITEM.NAME
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.PRICE
     *
     * @return the value of PUBLIC.ITEM.PRICE
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.PRICE
     *
     * @param price the value for PUBLIC.ITEM.PRICE
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.SELLER_ID
     *
     * @return the value of PUBLIC.ITEM.SELLER_ID
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public Integer getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.SELLER_ID
     *
     * @param sellerId the value for PUBLIC.ITEM.SELLER_ID
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.DESCRIPTION
     *
     * @return the value of PUBLIC.ITEM.DESCRIPTION
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.DESCRIPTION
     *
     * @param description the value for PUBLIC.ITEM.DESCRIPTION
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }
}