package com.itizwhatitiz.geliuparduotuve.mybatis.dao;

import com.itizwhatitiz.geliuparduotuve.mybatis.model.Item;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    Item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    List<Item> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Sat May 27 08:42:50 EEST 2023
     */
    int updateByPrimaryKey(Item record);
}